<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-06 08:23

$extensionPath = t3lib_extMgm::extPath('db_list');
return array(
	'tx_dblist_localrecordlist' => $extensionPath . 'class.tx_dblist_localrecordlist.php',
	'tx_dblist_recordlist' => $extensionPath . 'class.tx_dblist_recordlist.php',
	'tx_dblist_script' => $extensionPath . 'class.tx_dblist_script.php',
);
?>